version: "3.3"
services:
    pubsub:
        image: google/cloud-sdk:latest
        command: ["gcloud", "beta", "emulators", "pubsub", "start", "--host-port=0.0.0.0:8085", "--project=test"]
        ports:
        - "8085:8085"
        
    mongodb:
        image : mongo
        container_name: mongodb
        ports:
        - 27017:27017

    tracing:
        image: docker.io/jaegertracing/all-in-one:1.16
        ports:
            - "9411:9411"
            - "16686:16686"
            - "5778:5778"
        environment:
            # Enable Zipkin collector compatability.
            COLLECTOR_ZIPKIN_HTTP_PORT: 9411